import Head from 'next/head'
import WithSubnavigation from '@/components/sidebar'
import LargeWithLogoLeft from '@/components/footer'
import WithBackgroundImage from '@/components/home'
import SimpleThreeColumns from '@/components/features'
import SplitWithImage from '@/components/features'
import BasicStatistics from '@/components/features/second'
import SplitWithImage2 from '@/components/features/third'
import CaptionCarousel from '@/components/features/fourth'
import ArticleList from '@/components/features/fifth'


export default function Home() {
  return (
    <>
      <Head>
        <title>Hamza AL HOUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <WithSubnavigation/>


      <WithBackgroundImage/>
      <SplitWithImage/>
      <BasicStatistics/>
      <SplitWithImage2/>
      <CaptionCarousel/>
      <ArticleList />

      <LargeWithLogoLeft/>
      
      

      </main>
    </>
  )


}






