import Head from 'next/head'
import WithSubnavigation from '@/components/sidebar'
import LargeWithLogoLeft from '@/components/footer'
import WithBackgroundImage from '@/components/services/index'

import SplitWithImage from '@/components/services/second'
import SplitWithImage3 from '@/components/services/third'
import SplitWithImage4 from '@/components/services/fourth'




export default function Home() {
  return (
    <>
      <Head>
        <title>Allain-terrieur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <WithSubnavigation/>


      <WithBackgroundImage/>
      <SplitWithImage/>
      <SplitWithImage3/>
      <SplitWithImage4/>
    
      

      <LargeWithLogoLeft/>
      
      

      </main>
    </>
  )


}






